spring.application.name=socialMediaBE
spring.datasource.url=jdbc:postgresql://localhost:5432/socialMedia
spring.datasource.username=postgres
spring.datasource.password=minhduc113
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=a2e40eba61e3cbdc88d4ae0c3cd308aa
jwt.expiration=86400000